#!/usr/bin/bash

NETBOX_VERSION="v4.0.5"

PATH=/opt/local/gnu/bin:/opt/local/bin:/opt/local/sbin:/usr/bin:/usr/sbin

# Exit if any command fails
set -o errexit

echo "* Use default python 3.11"
pkg_alternatives manual python311
pkg_alternatives manual py311-pip

echo "* Remove used pgsql stuff from base"
rm -rf /var/pgsql/*

echo "* Configuring image specific packages."
mkdir -p /{opt,var}/netbox

# TODO: create a pkgsrc pkg with all dependencies
echo "* Install build dependencies"
pkgin -y install build-essential rust

echo "* Download and extract netbox to /opt/netbox"
curl -L "https://github.com/netbox-community/netbox/archive/refs/tags/${NETBOX_VERSION}.tar.gz" | gtar xz -C /opt/netbox --strip-components=1

echo "* Add netbox user"
groupadd netbox
useradd -d /opt/netbox -c "netbox user" -s /usr/bin/false -g netbox netbox

echo "* Install netbox requirements"
python3 -m venv /opt/netbox/venv --system-site-packages

echo "* Copy configuration template"
cp /tmp/configuration.py /opt/netbox/netbox/netbox/
cp /opt/netbox/contrib/gunicorn.py /opt/netbox/netbox/

echo "* Setup permissions for netbox folder"
chown -R netbox:netbox /{opt,var}/netbox

gsed -i '/nh3.*/d' /opt/netbox/requirements.txt
sudo -u netbox \
    TMPDIR=/var/tmp \
    /opt/netbox/venv/bin/pip3 install -r /opt/netbox/requirements.txt

echo "* Remove build dependencies"
pkgin -y remove build-essential rust
pkgin -y autoremove

echo "* Cleanup home/admin because of delegate dataset usage"
rm -rf /home/admin/.[^.]*

echo "* Cleaning up"
rm -rf /root/*
sm-prepare-image -y
